config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :user, skip: [], path: '', controllers: { registrations: 'registrations'}
  get 'persons/profile', as: 'user_root'

  root 'posts#index'
  
  #profile
  get '/view/:id', to: 'profile#show', as: 'view_profile'
  get '/profile/edit', to: 'profile#edit'
  patch '/profile/update', to: 'profile#update'
  get '/view_all', to: 'profile#show_all'

  resources :posts do
    resources :likes, only: [:create, :destroy]
    resources :comments
  end

  # delete '/posts/:post_id/likes/:id', to: 'likes#destroy'

  #followings
  get '/follows/:id', to: 'follows#show', as: 'follows'
  post '/follow/:id', to: 'follows#create', as: 'follow'
  delete '/unfollow/:id', to: 'follows#destroy', as: 'unfollow'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post

  validates :username, presence: true
  validates :body, presence: true
end

app/models/follow.rb
class Follow < ActiveRecord::Base

  extend ActsAsFollower::FollowerLib
  extend ActsAsFollower::FollowScopes

  # NOTE: Follows belong to the "followable" and "follower" interface
  belongs_to :followable, polymorphic: true
  belongs_to :follower,   polymorphic: true

  def block!
    self.update_attribute(:blocked, true)
  end

end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :post
  belongs_to :user
end

app/models/post.rb
class Post < ApplicationRecord
  attr_accessor :image

  has_attached_file :image, styles: { big: '500x500>', medium: '300x300>', thumb: '100x100>' },
                            escape_url: false,
                            url: '/assets/posts/:id/:style/:basename.:extension',
                            path: ':rails_root/public/assets/posts/:id/:style/:basename.:extension'

  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy

  validates :title, presence: true
  validates :body, presence: true, length: { minimum: 10 }
  validates_attachment :image, content_type: { content_type: ['image/jpg', 'image/jpeg', 'image/png', 'image/gif'] }

  belongs_to :user

end

app/models/profile.rb
class Profile < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  enum role: [:user, :vip, :admin], _suffix: :role
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :posts, dependent: :destroy
  has_many :likes, dependent: :destroy

  has_one :profile, dependent: :destroy

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_attached_file :avatar, :styles => { :medium => "300x300>", :thumb => "100x100#" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/

  validates :username, presence: true
  validates :email, presence: true

    
  acts_as_followable
  acts_as_follower

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pundit::Authorization
  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized

  private

  def user_not_authorized
    flash[:warning] = 'You are not authorized to perform this action.'
    redirect_to(request.referrer || root_path)
  end

  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(_resource)
    root_path
  end

  def after_sign_up_path_for(_resource)
    root_path
  end

  def after_sign_out_path_for(_resource)
    root_path
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up) do |u|
      u.permit(:username, :email, :password, :avatar, :password_confirmation)
    end
    devise_parameter_sanitizer.permit(:account_update) do |u|
      u.permit(:username, :email, :password, :current_password, :avatar)
    end
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!

  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.create(comment_params)
    redirect_to post_path(@post)
  end

  private

  def comment_params
    params.require(:comment).permit(:username, :body)
  end
end

app/controllers/follows_controller.rb
class FollowsController < ApplicationController
  before_action :authenticate_user!

  def show
    @user = User.find(params[:id])

    @following_count = @user.follow_count
    @follower_count = @user.followers_count

    @followings = @user.all_following
    @followers = @user.followers
  end

  def create
    user = User.find(current_user.id)
    followed_user = User.find(params[:id])
    user.follow(followed_user)
    respond_to do |format|
      format.js
    end
  end

  def destroy
    user = User.find(current_user.id)
    followed_user = User.find(params[:id])
    user.stop_following(followed_user)
    respond_to do |format|
      format.js
    end
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :authenticate_user!
  
  before_action :find_post
  before_action :find_like, only: [:destroy]

  def create
    if already_liked?
      flash[:notice] = "You can't like more than once"
    else
      @post.likes.create(user_id: current_user.id)
    end
    redirect_to post_path(@post)
  end

  def find_like
    @like = @post.likes.find(params[:id])
  end

  def destroy
    if !already_liked?
      flash[:notice] = 'Cannot unlike'
    else
      @like.destroy
    end
    redirect_to post_path(@post)
  end

  private

  def already_liked?
    Like.where(user_id: current_user.id, post_id:
    params[:post_id]).exists?
  end

  def find_post
    @post = Post.find(params[:post_id])
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!

  def index
    @posts = Post.includes(:user).all
    authorize @posts
  end

  def show
    @post = Post.includes(:user).includes(:likes).find(params[:id])
  end

  def new
    @post = Post.new
    authorize @post
  end

  def create
    @post = current_user.posts.new(post_params)
    authorize @post
    if @post.save
      redirect_to @post
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @post = Post.find(params[:id])
    authorize @post
  end

  def update
    @post = Post.find(params[:id])
    authorize @post  
    if @post.update(post_params)
      redirect_to @post
    else

      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @post = Post.find(params[:id])
    authorize @post
    @post.destroy

    redirect_to root_path, status: :see_other
  end

  private

  def post_params
    params.require(:post).permit(:title, :body, :user_id, :image_file_name, :image)
  end
end

app/controllers/profile_controller.rb
class ProfileController < ApplicationController
  before_action :authenticate_user!

  def show
    id = params[:id]

    @user = User.find(id)

    @following_count = @user.follow_count
    @follower_count = @user.followers_count

    @profile = User.select(:name, :bio, 'profiles.id').joins(:profile).find_by('users.id' => id)

    @following_posts = Post.includes(:user).where('user_id' => @user.all_following)

    @all_posts = Post.joins(:user).select(:id, :title, :body, :image_file_name, :created_at, :updated_at,
                                          :user_id).where('users.id' => id).order('posts.updated_at').reverse_order
  end

  def update
    @pf = Profile.find_by(user_id: current_user.id)
    @pf.update(name: pf_params[:name], bio: pf_params[:bio])
    redirect_to view_profile_path(current_user.id)
  end

  def edit
    @profile = Profile.find_by(user_id: current_user.id)
  end

  protected

  def pf_params
    params.require(:profile).permit(:name, :bio)
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  def create
    super do |r|
      Profile.create(name: 'Your name', bio: 'Your bio', user_id: r.id)
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/persons_helper.rb
module PersonsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/roles_helper.rb
module RolesHelper
  def has_role?(role)
    current_user && current_user.has_role?(role)
  end
end

app/views/follows/_follow_button.html.erb
<% if current_user.following?(@user) %>
  <%= button_to 'Unfollow', unfollow_path(profile_id), method: :delete %>
<% else %>
  <%= button_to 'Follow', follow_path(profile_id), method: :post %>
<% end %>

app/views/follows/show.html.erb
<div class="container">

  <div>Following</div>
  <div class="list-group">
    <% @followings.each do |f| %>
      <li class="list-group-item">
        <%= link_to view_profile_path(f.id), method: :get do %>
          <div><%= f.profile.name %></div>
        <% end %>
      </li>
    <% end %>
  </div>
  <div>Followers</div>
  <div class="list-group">
    <% @followers.each do |f| %>
      <li class="list-group-item">
          <%= f.email %>
      </li>
    <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Foto4ka</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
     
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <main class="flex justify-center w-full">
      <header id="header" class="flex items-center h-28">
        <a href=<%= root_path %>>
          <%= image_tag "LogoSample_ByTailorBrands.jpg"%>
        </a>
        <%= link_to "Главная", root_path %>
        <% if user_signed_in? %>
          <span id="greeting">Здравствуйте, <%= current_user.username %></span>
          <%= link_to 'Выйти', destroy_user_session_path, :method => :delete %>
        <% else %>
          <%= link_to 'Войти', new_user_session_path %> или <%= link_to 'Зарегистрироваться', new_user_registration_path %>
        <% end %>
      </header>
      <div id="content" class="container flex flex-col justify-center mx-auto  pb-20">
        <%= yield %>
      </div>
      <footer class="self-end">
        <a href=<%= root_path %>>
          2022 Foto4ka
        </a>
      </footer>
    </main>
    <script type="module" src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.esm.js"></script>
    <script nomodule src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.js"></script>
  </body>
</html>

app/views/persons/profile.html.erb
<div class="user-content" style="display:flex; gap: 16px"> 
    <div class="user-info" style="flex-basis: 33%">
        <h1>User: <%= current_user.username %></h1>

        <div style="width: 150px;height:150px">
            <%= image_tag current_user.avatar.url(:thumb), :class=>"rounded-full" %>
        </div>    
            
        <p class="notice"><%= notice %></p>
        <p class="alert"><%= alert %></p>
    </div>

    <div class="follower-content">

    </div>

</div>

app/views/posts/_form.html.erb
<%= form_with :html => {:multipart => true}, model: @post do |form| %>
  <div>
    <%= form.label :title %><br>
    <%= form.text_field :title %>
    <% @post.errors.full_messages_for(:title).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.label :body %><br>
    <%= form.text_area :body %><br>
     <% @post.errors.full_messages_for(:body).each do |message| %>
      <div><%= message %></div>
    <% end %>
 
    <%= form.file_field :image %>
    <% @post.errors.full_messages_for(:image).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

    <button class="bg-lime-700 hover:bg-lime-900 rounded p-2 text-white cursor-pointer"><%= form.submit %></button>
<% end %>

app/views/posts/edit.html.erb
<h1>Edit Post</h1>

<%= render "form", post: @post %>

app/views/posts/index.html.erb
<div class="posts-container">
    <ul>
    <% @posts.each do |post|%>
        <li class="post bg-grey">
            <a class="text-black underline" href="<%= post_path(post) %>">
                <div class="bg-slate-50 flex flex-col gap-4 rounded p-4">
                    <h2 class="text-black"><%=post.title%></h2>
                    <%= image_tag post.image.url(:big), :class=>"rounded post-image" %>            
                    <p class="text-slate-500"><%=post.body%></p>
                    <p><%= post.likes.count %> <%= (post.likes.count) == 1 ? 'Like' : 'Likes'%></p>
                    <div class="flex items-center gap-2">
                    <%= image_tag post.user.avatar.url(:thumb), :class=>"rounded-full small-avatar" %>
                    <p class=" text-black"><%= post.user.username %></p>
                    </div>
                </div>
            </a>
        </li>

    <%end%>
    </ul>
    <div class="bg-white width-auto add-post">
       <%= link_to "Добавить пост", new_post_path, :class=>"add-post-btn" %>
    </div>
</div>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render "form", post: @post %>

app/views/posts/show.html.erb
<%= flash[:error] %>
<div class="post-content bg-slate-50 flex justify-start gap-4 rounded p-4">
  <div class="post-image">
    <%= image_tag @post.image.url (:big), :class=>"rounded" %>
  </div>
  <div class="flex flex-col gap-4 post-data">
    <h2 class="text-black"><strong><%= @post.title %></strong></h2>
    <p class="text-black"><%= @post.body %></p>
    <p><%= @post.likes.count %> <%= (@post.likes.count) == 1 ? 'Like' : 'Likes'%></p>
    <% pre_like = @post.likes.find { |like| like.user_id == current_user.id} %>
    <% if pre_like %>
      <%= button_to 'Unlike post', post_like_path(@post, pre_like), method: :delete %>
    <% else %>
      <%= button_to 'Like post', post_likes_path(@post), method: :post %>
    <% end %>
    <div class="flex gap-4">
    <%= link_to view_profile_path(@post.user), method: :get do %>
      <%= image_tag @post.user.avatar.url(:thumb), :class=>"rounded-full small-avatar" %>
      <p class="text-black"><%= @post.user.username %></p>
    <%end%>
    </div>
    
    <% if current_user == @post.user || current_user.role == 'admin'%>
    <ul class="flex gap-4">
        <li class="underline"><%= link_to "Редактировать", edit_post_path(@post)%></li>
        <li class="underline"><%= link_to "Удалить", post_path(@post), data: {
                          turbo_method: :delete,
                          turbo_confirm: "Are you sure?"
                        } %></li>
    </ul>
    <% end %>
  </div>
  <div class="post-comments">
    <h2><strong>Комментарии</strong></h2>
    <% @post.comments.each do |comment| %>
      <p>
        <strong>Username:</strong>
        <%= comment.username %>
      </p>

      <p>
        <strong>Comment:</strong>
        <%= comment.body %>
      </p>
    <% end %>

    <h2>Add a comment:</h2>
    <%= form_with model: [ @post, @post.comments.build ] do |form| %>
      <p>
        <%= form.label :username %><br>
        <%= form.text_field :username %>
      </p>
      <p>
        <%= form.label :body %><br>
        <%= form.text_area :body %>
      </p>
      <p>
        <%= form.submit %>
      </p>
    <% end %>
  </div>
</div>